CREATE TABLE IF NOT EXISTS requests (
  id SERIAL PRIMARY KEY,
  app_name VARCHAR(255) NOT NULL,
  version VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  submitter VARCHAR(255) NOT NULL,
  approver VARCHAR(255),
  blob_paths JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
